### ISSUE TITLE
EVEX instructions with immediate displacements are encoded incorrectly

### ISSUE THREAD

**Issue by CatsAreFluffy** [NewDefectus/defAsm#28]
EVEX vector instructions with 1-byte displacements scale the displacement by the operand length. For example, `vmovdqu8 64(%rdi), %zmm0` assembles to `62 F1 7F 48 6F 47 40` but it should assemble to `62 F1 7F 48 6F 47 01`, and
`vmovdqu8 1(%rdi), %zmm0` assembles to `62 F1 7F 48 6F 47 01` but it should assemble to `62 F1 7F 48 6F 87 01 00 00 00`.
This can lead to some instructions having shorter EVEX encodings than VEX encodings. For example, `vpaddb 256(%rdi), %ymm0, %ymm0` assembles to `C5 FD FC 87 00 01 00 00` but it would be shorter as `62 E1 7D 20 FC 47 08`.

**Comment by NewDefectus** [comment]
Fixed :)

Regarding choosing the shorter EVEX encoding instead of the VEX, this is not something most assemblers do, and because this would break the `opcodes.js` test in a rather annoying way I'm choosing to follow the convention. However for the sake of completeness I added an `evex` prefix (borrowed from MASM) that allows you to manually request the EVEX encoding, like this:

![image](https://github.com/NewDefectus/defasm/assets/36775845/8e5d2349-47ef-4694-a47a-1bc32e076747)
